chess_app/models/__init__.py
from chess_app.models.game import *
from chess_app.models.user import *

chess_app/models/game.py
from datetime import datetime
import uuid
import logging

class Game:

    def __init__(self):
        self.id = uuid.uuid4()
        self.start = None
        self.end = None
        self.white = None
        self.black = None
        self.turn = None
        self.board = None
        self.opponent = None
        self.logger = logging.getLogger(__name__)

    @staticmethod
    def new(white, black):
        game = Game()
        game.start = datetime.now()
        game.end = None
        game.white = white
        game.black = black
        game.turn = white
        return game

    def color(self, userid):
        if self.white == userid:
            return 'white'
        if self.black == userid:
            return 'black'
        raise ValueError('User is not part of this game')

    @staticmethod
    def build_from_invite(user1, user2, user2_color):
        if user2_color == 'black':
            return Game.new(user1, user2)
        else:
            return Game.new(user2, user1)

chess_app/models/user.py
from flask import current_app
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import BadSignature, SignatureExpired
from werkzeug.security import check_password_hash, generate_password_hash


class Permission:
    GENERAL = 0x01
    ADMINISTER = 0xff


class Role:

    def __init__(self):
        self.id = None
        self.name = None
        self.index = None
        self.is_default = None
        self.permissions = None

    @staticmethod
    def create(name, index, is_default, permissions):
        r = Role()
        r.name = name
        r.index = index
        r.is_default = is_default
        r.permissions = permissions
        return r

    @staticmethod
    def default():
        return Role.create('User', 'main', True, Permission.GENERAL)

    @staticmethod
    def admin():
        return Role.create('Administrator', 'admin', False, Permission.ADMINISTER)

    def __repr__(self):
        return '<Role \'%s\'>' % self.name


class User:

    def __init__(self):
        self.userid = None
        self.username = None
        self.first = None
        self.last = None
        self.email = None
        self.password_hash = None
        self.confirmed = None
        self.roleid = None

    @staticmethod
    def create(username, first, last, email, password, roleid):
        user = User()
        user.username = username
        user.first = first
        user.last = last
        user.email = email
        user.password_hash = generate_password_hash(password)
        user.confirmed = False
        user.roleid = roleid
        return user

    def full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def can(self, permissions):
        return self.role is not None and \
            (self.role.permissions & permissions) == permissions

    def is_admin(self):
        return self.can(Permission.ADMINISTER)

    @property
    def password(self):
        raise AttributeError('`password` is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=604800):
        """Generate a confirmation token to email a new user."""

        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def generate_email_change_token(self, new_email, expiration=3600):
        """Generate an email change token to email an existing user."""
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'change_email': self.id, 'new_email': new_email})

    def generate_password_reset_token(self, expiration=3600):
        """
        Generate a password reset change token to email to an existing user.
        """
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'reset': self.id})

    def confirm_account(self, token):
        """Verify that the provided token is for this user's id."""
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except (BadSignature, SignatureExpired):
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        return True

    def change_email(self, token):
        """Verify the new email for this user."""
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except (BadSignature, SignatureExpired):
            return False
        if data.get('change_email') != self.id:
            return False
        new_email = data.get('new_email')
        if new_email is None:
            return False
        if self.query.filter_by(email=new_email).first() is not None:
            return False
        self.email = new_email
        return True

    def reset_password(self, token, new_password):
        """Verify the new password for this user."""
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except (BadSignature, SignatureExpired):
            return False
        if data.get('reset') != self.id:
            return False
        self.password = new_password
        # db_session.add(self)
        # db_session.commit()
        return True

chess_app/__init__.py
from .models import User, Role, Permission
from .config import Config

chess_app/auth.py
from functools import wraps
from flask import request, redirect, url_for
from chess_app.config import Config
from datetime import datetime, timedelta
from jwt import decode, encode, DecodeError
import logging

logger = logging.getLogger(__name__)


def generate_token(user):
    logger.debug('Issuing token for user %s', user.username)
    return encode({
        'username': user.username,
        'userid': user.userid,
        # 'role': user.role.name,
        'expires': str(datetime.now() + timedelta(hours=3))},
        Config.SECRET_KEY, algorithm='HS256')


def validate(token):
    try:
        decoded = decode(token, Config.SECRET_KEY, verify=True)
        expiration = datetime.strptime(decoded['expires'], "%Y-%m-%d %H:%M:%S.%f")
        if expiration < datetime.now():
            return False
        return True
    except KeyError:
        raise Exception("You got yourself a malformed token, there.")
    except DecodeError:
        logger.critical('Failed to decode token: %s', str(token))
        return False


def authenticate(func):
    @wraps(func)
    def decorated(*args, **kwargs):
        token = request.cookies.get(Config.COOKIE)
        if not token or not validate(token):
            # resp = make_response()
            # resp.headers["WWW-Authenticate"] = "Basic realm=Login Required"
            # return resp
            return redirect(url_for('accounts.login'))
        return func(*args, **kwargs)
    return decorated

chess_app/controllers/__init__.py
from .gamecontroller import *
from .homecontroller import *
from .logincontroller import *

chess_app/controllers/gamecontroller.py
from flask import render_template, request, make_response, jsonify, Blueprint
from chess_app import request_state
from chess_app.auth import authenticate
from chess_app.models import Game
from chess_app.services.game_service import GameService
from chess_app.services.user_service import UserService
import logging
import json

games_blueprint = Blueprint('games', __name__, template_folder='templates')
log = logging.getLogger(__name__)


@games_blueprint.route('/games/invite', methods=['GET'])
def invite():
    return render_template('invite.html')


@games_blueprint.route('/games', methods=['GET'])
@authenticate
def list_games(game_service=GameService()):
    userid = request_state.current_userid()
    games = game_service.list_games(userid)
    args = [(game.id, game.start, game.color(userid), game.opponent) for game in games]
    return make_response(render_template('game_list.html', games=list(args)), 200)

    
@games_blueprint.route('/games/<uuid:gameid>')
@authenticate
def render_game(gameid):
    orientation = request.args.get('color')
    return render_template('game.html', gameid=gameid, orientation=orientation)


@games_blueprint.route('/games/<uuid:gameid>/board')
def load_game(gameid, game_service=GameService()):
    board = game_service.find_game(gameid).board
    return make_response(jsonify(board=board), 200)


@games_blueprint.route('/games/<uuid:gameid>/board', methods=['POST'])
def save_board(gameid, game_service=GameService()):
    board = json.loads(request.form['board'])
    # log.debug(request.form['board'])
    game_service.save_board(gameid, board)
    return make_response(jsonify(message="move was saved"), 200)


@games_blueprint.route('/games/new/', methods=['POST'])
@authenticate
def create(game_service=GameService(), user_service=UserService()):
    opponent = request.form['username']
    color = request.form['color']
    userid1 = request_state.current_userid()
    userid2 = user_service.get_by_username(opponent).userid
    game = Game.build_from_invite(userid1, userid2, color)
    game_service.new_game(game)
    return make_response("created a game", 200)

chess_app/controllers/homecontroller.py
from flask import render_template, Blueprint

home_blueprint = Blueprint('home', __name__, template_folder='templates')


@home_blueprint.route('/')
def page_index():
    return render_template('index.html', selected_menu_item="index")

chess_app/controllers/logincontroller.py
from flask import render_template, request, jsonify, make_response, \
    redirect, url_for, Blueprint

from chess_app import auth
from chess_app.services.user_service import UserService
from chess_app.models.user import User
from chess_app.config import Config
import logging

account_blueprint = Blueprint('accounts', __name__)
logger = logging.getLogger(__name__)


@account_blueprint.route('/accounts', methods=['GET'])
def register():
    return render_template('create_account.html')


@account_blueprint.route('/accounts', methods=['POST'])
def create_account(user_service=UserService()):
    username = request.form['username']
    password = request.form['password']
    email = request.form['email']
    first_name = request.form['first_name']
    last_name = request.form['last_name']
    user = user_service.get_by_username(username)
    if user is None:
        roleid = user_service.get_default_role().id
        user = User.create(username=username, password=password, email=email,
                           first=first_name, last=last_name, roleid=roleid)
        user_service.add_user(user)
    else:
        return make_response("Account exists", 409)
    return make_response("Account created", 201)


@account_blueprint.route('/login', methods=['GET'])
def login():
    return render_template('login.html')


@account_blueprint.route('/login', methods=['POST'])
def login_submit(user_service=UserService()):
    username = request.form['username']
    password = request.form['password']
    user = user_service.get_by_username(username)
    if user is None:
        return make_response(jsonify(message="User not found", username=username), 404)
    if not user.verify_password(password):
        return make_response("Unauthorized", 401)
    else:
        token = auth.generate_token(user)
        logger.debug('logging in user=%s', username)
        # response = make_response(jsonify(message="success", token=str(token, 'utf-8')), 200)
        response = make_response(render_template('index.html'))
        response.set_cookie(Config.COOKIE, token)
        return response


@account_blueprint.route('/logout')
def logout():
    response = make_response(redirect(url_for('home.page_index')))
    response.set_cookie(Config.COOKIE, '', expires=0)
    return response

chess_app/data_access/__init__.py
from .game_repository import *
from .user_repository import *

chess_app/templates/create_account.html
{% extends "layout.html" %}
{% block body %}
  <h2>Create account</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('accounts.create_account') }}" method=post>
    <dl>
      <dt>First name:
      <dd><input type=text name=first_name>
      <dt>Last name:
      <dd><input type=text name=last_name>
      <dt>Email:
      <dd><input type=text name=email>
      <dt>Username:
      <dd><input type=text name=username>
      <dt>Password:
      <dd><input type=password name=password>
      <dd><input type=submit value=Create>
    </dl>
  </form>
{% endblock %}

chess_app/templates/game.html
{% extends "layout.html" %}
{% block childimport %}
    <script src={{url_for('static', filename='js/chessboard-0.3.0.js')}}></script>
    <script src={{ url_for('static', filename='js/gameplay.js')}}></script>
    <script src={{ url_for('static', filename='js/chess.js')}}></script>
    <link rel="stylesheet" href="{{url_for('static', filename='css/chessboard-0.3.0.css')}}"/>
{% endblock %}
{% block body %}

    <div id="gameid">{{ gameid }}</div>
    <div id="orientation" style="visibility: hidden;">{{ orientation }}</div>
    <script>
        var board;
        var chess;
    </script>
    <div id="board" style="width: 500px"></div>
    <button id="move_button" onclick="sendBoardState()">Submit!</button>
    <div id="test_move"></div>
{% endblock %}

chess_app/templates/game_list.html
{% extends "layout.html" %}
{% block childimport %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/chessboard-0.3.0.css')}}"/>
{% endblock %}
{% block body %}

    <h1>Games in play:</h1>
    <ol>
        {% for game in games %}
        <li><a href={{url_for('games.render_game', gameid=game[0])+'?color='+game[2]}}>
            {{ game[0] }}
            </a> <br /> Last move: {{ game[1] }} Opponent: {{ game[3] }}
        </li>
        {% endfor %}
    </ol>

{% endblock %}

chess_app/templates/index.html
{% extends "layout.html" %}


{% block body %}

<h2>This is the homepage</h2>

{% endblock %}

chess_app/templates/invite.html
{% extends "layout.html" %}
{% block body %}
  <h2>Invite</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('games.create') }}" method=post>
    <dl>
      <dt>Invite to game:
      <dd><input type=text name=username>
        <dd><input type="radio" name="color" value="white"> White<br></dd>
        <dd><input type="radio" name="color" value="black"> Black<br></dd>
      <dd><input type=submit value=Invite>
    </dl>
  </form>
{% endblock %}

chess_app/templates/layout.html
<!doctype html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %}

    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}"/>
    <title>Magic Internet Chess</title>
    {% endblock %}
    {% block childimport %}
    {% endblock %}
</head>
<body>
    {% block scripts %}
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    {% endblock %}

        {% block navigation %}
        <!-- Static navbar -->
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <div class="navbar-header">
                        <a href="#" class="navbar-brand">e-chess</a>
                    </div>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        {% if selected_menu_item == "index" %}
                        <li class="active"><a href="#">Home</a></li>
                        {% else %}
                        <li><a href="{{url_for('home.page_index')}}">Home</a></li>
                        {% endif %}

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">Games <span class="caret"></span></a>
                            <ul class="dropdown-menu">

                            {% if selected_menu_item == "newgame" %}
                            <li class="active"><a href="#">New Game</a></li>
                            {% else %}
                            <li><a href="{{url_for('games.invite')}}">New Game</a></li>
                            {% endif %}

                            {% if selected_menu_item == "summary" %}
                            <li class="active"><a href="#">View All</a></li>
                            {% else %}
                            <li><a href="{{url_for('games.list_games')}}">View</a></li>
                            {% endif %}

                            </ul>
                        </li>


                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">Account <span class="caret"></span></a>
                            <ul class="dropdown-menu">

                                {% if request.cookies.get('ca_session') == None %}
                                    {% if selected_menu_item == "login" %}
                                    <li><a href="#">login</a></li>
                                    {% else %}
                                    <li><a href="{{url_for('accounts.login')}}">Login</a></li>
                                    {% endif %}
                                    {% if selected_menu_item == "register" %}
                                    <li><a href="#">Register</a></li>
                                    {% else %}
                                    <li><a href="{{url_for('accounts.register')}}">Register</a></li>
                                    {% endif %}
                                {% else %}
                                    {% if selected_menu_item == "logout" %}
                                    <li><a href="#">logout</a></li>
                                    {% else %}
                                    <li><a href="{{url_for('accounts.logout')}}">Logout</a></li>
                                    {% endif %}
                                {% endif %}


                            </ul>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
            <!--/.container-fluid -->
        </nav>
        {% endblock %}

      {% block body %}{% endblock %}

</body>

chess_app/templates/login.html
{% extends "layout.html" %}
{% block body %}
  <h2>Login</h2>
  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('accounts.login_submit') }}" method=post>
    <dl>
      <dt>Username:
      <dd><input type=text name=username>
      <dt>Password:
      <dd><input type=password name=password>
      <dd><input type=submit value=Login>
    </dl>
  </form>
{% endblock %}